package main

import (
	"archive/zip"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/superops-team/okf/pkg/okf"
	"github.com/superops-team/okf/pkg/parser"
	"github.com/superops-team/okf/pkg/query"
)

// P2 integration tests for the document pre-stage conversion layer.
// Fixtures are generated by pkg/convert/testdata/gen_fixtures.py (git-committed).

const fixtureDir = "../../pkg/convert/testdata"

func fixture(name string) string { return filepath.Join(fixtureDir, name) }

func newKB(t *testing.T) string {
	kb := filepath.Join(t.TempDir(), "kb")
	if err := os.MkdirAll(kb, 0o755); err != nil {
		t.Fatal(err)
	}
	return kb
}

// --- S10: single document file ---

func TestCmdAddSingleDocument(t *testing.T) {
	kb := newKB(t)
	if code := cmdAdd([]string{"-dir", kb, "-silent", fixture("sample.pdf")}); code != 0 {
		t.Fatalf("cmdAdd = %d, want 0", code)
	}
	prod := filepath.Join(kb, "sample.pdf.md")
	data, err := os.ReadFile(prod)
	if err != nil {
		t.Fatalf("product %s missing: %v", prod, err)
	}
	if !strings.Contains(string(data), "OKF PDF Fixture") {
		t.Errorf("product body missing PDF text")
	}
	if !strings.Contains(string(data), "type: source") {
		t.Errorf("product frontmatter missing type: source")
	}
	if !strings.Contains(string(data), "Converted from sample.pdf (via pdf)") {
		t.Errorf("product description template wrong:\n%s", data)
	}
}

// --- S14: dry-run must not write ---

func TestCmdAddDryRunNoWrite(t *testing.T) {
	kb := newKB(t)
	if code := cmdAdd([]string{"-dir", kb, "-dry-run", "-silent", fixture("sample.docx")}); code != 0 {
		t.Fatalf("cmdAdd = %d, want 0", code)
	}
	// dry-run must not write anything at all (not even .metadata.json)
	entries, _ := os.ReadDir(kb)
	if len(entries) != 0 {
		names := make([]string, 0, len(entries))
		for _, e := range entries {
			names = append(names, e.Name())
		}
		t.Errorf("dry-run wrote into knowledge base: %v", names)
	}
}

// captureStdout runs fn while redirecting os.Stdout to a pipe and returns the
// captured output.
func captureStdout(t *testing.T, fn func()) string {
	t.Helper()
	old := os.Stdout
	r, w, err := os.Pipe()
	if err != nil {
		t.Fatal(err)
	}
	os.Stdout = w
	defer func() { os.Stdout = old }()
	fn()
	w.Close()
	os.Stdout = old
	data, _ := io.ReadAll(r)
	return string(data)
}

// --- S13/S20: re-import of an unchanged document is a no-change ---

func TestCmdAddReimportNoChange(t *testing.T) {
	kb := newKB(t)
	if code := cmdAdd([]string{"-dir", kb, "-silent", fixture("sample.xlsx")}); code != 0 {
		t.Fatalf("first cmdAdd = %d", code)
	}
	if code := cmdAdd([]string{"-dir", kb, "-silent", fixture("sample.xlsx")}); code != 0 {
		t.Fatalf("second cmdAdd = %d", code)
	}
	// no duplicate products: exactly one concept file
	concepts := 0
	filepath.Walk(kb, func(p string, info os.FileInfo, err error) error {
		if err == nil && !info.IsDir() && strings.HasSuffix(p, ".md") {
			concepts++
		}
		return nil
	})
	if concepts != 1 {
		t.Errorf("expected exactly 1 concept after re-import, got %d", concepts)
	}
}

// --- S27: summary reports converted documents ---

func TestCmdAddMixedReport(t *testing.T) {
	kb := newKB(t)
	out := captureStdout(t, func() {
		if code := cmdAdd([]string{"-dir", kb, fixture("sample.xlsx")}); code != 0 {
			t.Errorf("cmdAdd = %d, want 0", code)
		}
	})
	if !strings.Contains(out, "Converted (documents): 1") {
		t.Errorf("summary missing converted count; got:\n%s", out)
	}
	if _, err := os.Stat(filepath.Join(kb, "sample.xlsx.md")); err != nil {
		t.Fatalf("xlsx product missing: %v", err)
	}
}

// --- S11: mixed directory (md + documents, relative layout preserved) ---

func TestCmdAddMixedDirectory(t *testing.T) {
	src := t.TempDir()
	if err := os.MkdirAll(filepath.Join(src, "sub"), 0o755); err != nil {
		t.Fatal(err)
	}
	// a plain markdown file
	os.WriteFile(filepath.Join(src, "readme.md"), []byte("---\ntype: note\ntitle: \"r\"\n---\nmanual\n"), 0o644)
	// copy a docx at root and a pdf into a subdir
	if err := copyFile(fixture("sample.docx"), filepath.Join(src, "sample.docx")); err != nil {
		t.Fatal(err)
	}
	if err := copyFile(fixture("sample.pdf"), filepath.Join(src, "sub", "sample.pdf")); err != nil {
		t.Fatal(err)
	}
	kb := newKB(t)
	if code := cmdAdd([]string{"-dir", kb, "-silent", src}); code != 0 {
		t.Fatalf("cmdAdd = %d, want 0", code)
	}
	for _, p := range []string{"readme.md", "sample.docx.md", "sub/sample.pdf.md"} {
		if _, err := os.Stat(filepath.Join(kb, p)); err != nil {
			t.Errorf("knowledge base missing %s: %v", p, err)
		}
	}
}

// --- S12: conversion product naming ---

func TestConvertAndStage_Naming(t *testing.T) {
	staging, count, _, cleanup, err := convertAndStageDocuments(fixture("sample.pdf"))
	if err != nil {
		t.Fatal(err)
	}
	defer cleanup()
	if count != 1 {
		t.Fatalf("converted count = %d, want 1", count)
	}
	if _, err := os.Stat(filepath.Join(staging, "sample.pdf.md")); err != nil {
		t.Errorf("expected staging/sample.pdf.md (original name preserved), got err: %v", err)
	}
}

// --- S15: a failing conversion must not abort the batch ---

func TestConvertAndStage_Unsupported(t *testing.T) {
	dir := t.TempDir()
	// app.exe: not a supported document (skipped silently)
	// broken.pdf: supported extension but corrupt -> conversion fails and is
	//             skipped without aborting the batch (S15)
	// sample.docx: real document -> converted
	os.WriteFile(filepath.Join(dir, "app.exe"), []byte("MZ"), 0o644)
	os.WriteFile(filepath.Join(dir, "broken.pdf"), []byte("%PDF-fake"), 0o644)
	if err := copyFile(fixture("sample.docx"), filepath.Join(dir, "sample.docx")); err != nil {
		t.Fatal(err)
	}
	staging, count, _, cleanup, err := convertAndStageDocuments(dir)
	if err != nil {
		t.Fatal(err)
	}
	defer cleanup()
	if count != 1 { // only sample.docx converts successfully
		t.Errorf("converted count = %d, want 1", count)
	}
	if _, err := os.Stat(filepath.Join(staging, "sample.docx.md")); err != nil {
		t.Errorf("sample.docx.md missing: %v", err)
	}
	if _, err := os.Stat(filepath.Join(staging, "broken.pdf.md")); err == nil {
		t.Errorf("broken.pdf should be skipped, not staged")
	}
	if _, err := os.Stat(filepath.Join(staging, "app.exe")); err == nil {
		t.Errorf("unsupported app.exe should not be staged")
	}
}

// --- S19: staging cleanup ---

func TestConvertAndStage_Cleanup(t *testing.T) {
	staging, _, _, cleanup, err := convertAndStageDocuments(fixture("sample.docx"))
	if err != nil {
		t.Fatal(err)
	}
	cleanup()
	if _, err := os.Stat(staging); !os.IsNotExist(err) {
		t.Errorf("staging dir %s should be removed after cleanup", staging)
	}
}

// --- S26/S28: archive containing documents ---

func TestConvertAndStage_Archive(t *testing.T) {
	dir := t.TempDir()
	// build a zip with a markdown file, a docx at root and a pdf in a subdir
	zipPath := filepath.Join(dir, "bundle.zip")
	if err := buildTestZip(zipPath, map[string]string{
		"readme.md":      "---\ntype: note\ntitle: \"r\"\n---\narch md\n",
		"sample.docx":    fixture("sample.docx"),
		"sub/sample.pdf": fixture("sample.pdf"),
	}); err != nil {
		t.Fatal(err)
	}
	staging, count, _, cleanup, err := convertAndStageDocuments(zipPath)
	if err != nil {
		t.Fatal(err)
	}
	defer cleanup()
	if count != 2 {
		t.Errorf("converted count = %d, want 2", count)
	}
	for _, p := range []string{"readme.md", "sample.docx.md", "sub/sample.pdf.md"} {
		if _, err := os.Stat(filepath.Join(staging, p)); err != nil {
			t.Errorf("staging missing %s: %v", p, err)
		}
	}
}

func buildTestZip(path string, files map[string]string) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	zw := zip.NewWriter(f)
	for name, src := range files {
		var content []byte
		if st, serr := os.Stat(src); serr == nil && !st.IsDir() {
			content, err = os.ReadFile(src)
			if err != nil {
				return err
			}
		} else {
			content = []byte(src)
		}
		w, werr := zw.Create(name)
		if werr != nil {
			return werr
		}
		if _, werr := w.Write(content); werr != nil {
			return werr
		}
	}
	return zw.Close()
}

// --- S29: converted documents are searchable after import ---
// End-to-end: convert+import via cmdAdd, then run the same search path used
// by `okf search` (LoadBundle -> toQueryBundle -> query.SearchWithMatches).

func TestCmdAddDocumentsSearchable(t *testing.T) {
	src := t.TempDir()
	for _, f := range []string{"sample.pdf", "sample.docx", "sample.xlsx", "sample.pptx", "sample.html", "sample.csv", "sample.txt"} {
		if err := copyFile(fixture(f), filepath.Join(src, f)); err != nil {
			t.Fatal(err)
		}
	}
	kb := newKB(t)
	if code := cmdAdd([]string{"-dir", kb, "-silent", src}); code != 0 {
		t.Fatalf("cmdAdd = %d, want 0", code)
	}
	bundle, err := okf.LoadBundle(kb, okf.DefaultLoadOptions())
	if err != nil {
		t.Fatalf("LoadBundle: %v", err)
	}
	qb := toQueryBundle(bundle)
	cases := []struct {
		kw   string
		want string // expected product file
	}{
		{"body text", "sample.pdf.md"},
		{"Section One", "sample.docx.md"},
		{"banana", "sample.xlsx.md"},
		{"First slide", "sample.pptx.md"},
		{"Main Heading", "sample.html.md"},
		{"foo", "sample.csv.md"},
		{"Plain text", "sample.txt.md"},
	}
	for _, c := range cases {
		res := query.SearchWithMatches(qb, c.kw)
		if len(res) == 0 {
			t.Errorf("search(%q): no results, want %s", c.kw, c.want)
			continue
		}
		found := false
		for _, r := range res {
			if strings.HasSuffix(r.Concept.FilePath, c.want) {
				found = true
				break
			}
		}
		if !found {
			t.Errorf("search(%q): results %v, want %s", c.kw, res, c.want)
		}
	}
	// negative: unknown term must return nothing
	if res := query.SearchWithMatches(qb, "zzznonexistentword123"); len(res) != 0 {
		t.Errorf("search(zzznonexistentword123): got %d results, want 0", len(res))
	}
}

// --- title with special characters must survive frontmatter round-trip ---
// WrapConcept uses %q quoting; the resulting YAML must still be parseable by
// the OKF parser (quotes, backslashes, newlines are the risky cases).
func TestWrapFrontmatterSpecialTitle(t *testing.T) {
	title := "He said \"hi\" \\ done\nline2"
	body := wrapFrontmatter(title, "weird \"file\".pdf", "pdf", "some body")
	c, err := parser.ParseConceptBytes("weird.md", []byte(body))
	if err != nil {
		t.Fatalf("ParseConceptBytes with special title: %v\nbody:\n%s", err, body)
	}
	if !strings.Contains(c.Title, "He said") || !strings.Contains(c.Title, "done") {
		t.Errorf("title round-trip lost content: %q", c.Title)
	}
}

// --- tar.xz: IsArchive recognizes it but extraction must fail clearly ---
func TestExtractArchiveTarXZClearError(t *testing.T) {
	dir := t.TempDir()
	bad := filepath.Join(dir, "bundle.tar.xz")
	if err := os.WriteFile(bad, []byte("not really xz"), 0o644); err != nil {
		t.Fatal(err)
	}
	_, _, _, cleanup, err := convertAndStageDocuments(bad)
	defer func() {
		if cleanup != nil {
			cleanup()
		}
	}()
	if err == nil {
		t.Fatal("expected error for .tar.xz")
	}
	if !strings.Contains(err.Error(), ".tar.xz") {
		t.Errorf("error should name .tar.xz, got: %v", err)
	}
}

// --- S15b: a single document whose conversion fails must exit non-zero ---
func TestCmdAddAllConversionFailed(t *testing.T) {
	dir := t.TempDir()
	broken := filepath.Join(dir, "broken.pdf")
	if err := os.WriteFile(broken, []byte("%PDF-not-really"), 0o644); err != nil {
		t.Fatal(err)
	}
	kb := newKB(t)
	if code := cmdAdd([]string{"-dir", kb, "-silent", broken}); code == 0 {
		t.Errorf("cmdAdd = 0, want non-zero when the only document fails to convert")
	}
	// nothing must have been written into the knowledge base
	entries, _ := os.ReadDir(kb)
	if len(entries) != 0 {
		t.Errorf("knowledge base should stay empty, got %v", entries)
	}
}
