package tool

import (
	"context"
	"path/filepath"
	"strings"
	"testing"

	"github.com/superops-team/okf/pkg/okf"
)

// codeFileWorkflowContent mirrors the body generated by
// pkg/git/generator.go conceptFromSummary for a code_file concept. It carries
// no symbol_kind/qualified_name/start_line/end_line custom fields: the symbol
// range only appears in the generated symbol line.
const codeFileWorkflowContent = `## File: ` + "`pkg/agentconfig/workflow.go`" + `

## Code Metadata

**Schema Version:** 1

## Source

- Path: ` + "`pkg/agentconfig/workflow.go`" + `
- Language: ` + "`go`" + `
- Lines: 1-200

### Symbols

- ` + "`function` `RenderCodexMCPTOML` (exported) at `pkg/agentconfig/workflow.go:159-177`" + `
- ` + "`function` `RenderOtherTOML` (unexported) at `pkg/agentconfig/workflow.go:180-190`" + `
`

func newCodeFileWorkflowConcept() *okf.Concept {
	return &okf.Concept{
		Type:     "code_file",
		Title:    "workflow.go",
		Resource: "code://repo/pkg/agentconfig/workflow.go",
		Tags:     []string{"code", "generated", "go"},
		FilePath: "code_files/workflow.md",
		Content:  codeFileWorkflowContent,
		CustomFields: map[string]interface{}{
			"source_path": "pkg/agentconfig/workflow.go",
			"generated":   true,
			"generator":   "okf.git",
		},
	}
}

// TestFilteredConceptsCodeMetadataCombination verifies that a generated
// code_file concept (whose CustomFields lack symbol_kind / qualified_name)
// is still matched by FilePath + SymbolKind + QualifiedName filters because
// the symbol metadata lives only in the concept body.
func TestFilteredConceptsCodeMetadataCombination(t *testing.T) {
	concepts := []*okf.Concept{newCodeFileWorkflowConcept()}

	cases := map[string]queryFilters{
		"all together": {
			FilePath:      "pkg/agentconfig/workflow.go",
			SymbolKind:    "function",
			QualifiedName: "RenderCodexMCPTOML",
		},
		"file path alone":      {FilePath: "pkg/agentconfig/workflow.go"},
		"symbol kind alone":    {SymbolKind: "function"},
		"qualified name alone": {QualifiedName: "RenderCodexMCPTOML"},
		"language alone":       {Language: "go"},
	}
	for name, filters := range cases {
		t.Run(name, func(t *testing.T) {
			got := filteredConceptsForQuery(concepts, filters)
			if len(got) != 1 {
				t.Fatalf("filteredConceptsForQuery(%#v) = %d concepts, want 1", filters, len(got))
			}
			if got[0] != concepts[0] {
				t.Fatalf("filteredConceptsForQuery returned the wrong concept")
			}
		})
	}

	// A qualified name that does not appear in the body must not match.
	none := filteredConceptsForQuery(concepts, queryFilters{QualifiedName: "RenderCodexMCPTOML_Nonexistent"})
	if len(none) != 0 {
		t.Fatalf("nonexistent qualified name matched %d concepts, want 0", len(none))
	}
}

// TestRankConceptsSymbolLocationFromContent verifies that rankConcepts falls
// back to parsing the generated symbol line when start_line/end_line custom
// fields are absent (the code_file case).
func TestRankConceptsSymbolLocationFromContent(t *testing.T) {
	concepts := []*okf.Concept{newCodeFileWorkflowConcept()}

	hits := rankConcepts(concepts, "RenderCodexMCPTOML", queryFilters{})
	if len(hits) != 1 {
		t.Fatalf("rankConcepts returned %d hits, want 1", len(hits))
	}
	hit := hits[0]
	if hit.StartLine != 159 || hit.EndLine != 177 {
		t.Fatalf("hit lines = %d-%d, want 159-177 parsed from body", hit.StartLine, hit.EndLine)
	}
	if hit.SymbolKind != "function" {
		t.Fatalf("hit symbol kind = %q, want function", hit.SymbolKind)
	}
	if !strings.Contains(hit.QualifiedName, "RenderCodexMCPTOML") {
		t.Fatalf("hit qualified name = %q, want to contain RenderCodexMCPTOML", hit.QualifiedName)
	}
	if hit.Location != "pkg/agentconfig/workflow.go:159-177" {
		t.Fatalf("hit location = %q, want pkg/agentconfig/workflow.go:159-177", hit.Location)
	}
}

// TestContextExtractsSymbolBody verifies that Service.Context reads the
// source file using the parsed symbol range and returns the whole function
// body (multiple lines) rather than a single keyword line.
func TestContextExtractsSymbolBody(t *testing.T) {
	repo := initToolTestRepo(t)
	// The function spans 1-indexed lines 4-6 of the source file.
	mustWriteToolFile(t, filepath.Join(repo, "pkg", "agentconfig", "workflow.go"), `package agentconfig

// RenderCodexMCPTOML renders the codex MCP TOML config.
func RenderCodexMCPTOML() string {
	return "rendered-codex-body"
}

func OtherFunc() int {
	return 0
}
`)
	mustWriteToolFile(t, filepath.Join(repo, ".okf", "knowledge", "code", "workflow.md"), `---
type: code_file
title: workflow.go
description: workflow code file
resource: code://repo/pkg/agentconfig/workflow.go
tags:
  - code
  - generated
  - go
source_path: pkg/agentconfig/workflow.go
generated: true
generator: okf.git
---
## File: `+"`pkg/agentconfig/workflow.go`"+`

## Source

- Path: `+"`pkg/agentconfig/workflow.go`"+`
- Language: `+"`go`"+`

### Symbols

- `+"`function` `RenderCodexMCPTOML` (exported) at `pkg/agentconfig/workflow.go:4-6`"+`
- `+"`function` `OtherFunc` (unexported) at `pkg/agentconfig/workflow.go:8-9`"+`
`)

	svc := NewService(Config{RepoPath: repo})
	resp := svc.Context(context.Background(), ContextRequest{Query: "RenderCodexMCPTOML", BudgetTokens: 400})
	if !resp.OK {
		t.Fatalf("context OK = false, error = %#v", resp.Error)
	}
	result := resp.Result.(ContextResult)
	if len(result.Items) != 1 {
		t.Fatalf("context items = %d, want 1 (%#v)", len(result.Items), result.Items)
	}
	item := result.Items[0]
	if item.StartLine == 0 || item.EndLine == 0 {
		t.Fatalf("item lines = %d-%d, want parsed symbol range", item.StartLine, item.EndLine)
	}
	if !strings.Contains(item.Snippet, "func RenderCodexMCPTOML") {
		t.Fatalf("snippet = %q, want to contain the function signature", item.Snippet)
	}
	if !strings.Contains(item.Snippet, "rendered-codex-body") {
		t.Fatalf("snippet = %q, want to contain the function body", item.Snippet)
	}
	if strings.Contains(item.Snippet, "OtherFunc") {
		t.Fatalf("snippet = %q, should not contain the unrelated function", item.Snippet)
	}
}

// TestStatusReportsCodeConceptCount verifies that Status exposes the number of
// code_file concepts so an agent can tell whether code knowledge was generated.
func TestStatusReportsCodeConceptCount(t *testing.T) {
	repo := initToolTestRepo(t)
	mustWriteToolFile(t, filepath.Join(repo, ".okf", "knowledge", "code", "workflow.md"), `---
type: code_file
title: workflow.go
resource: code://repo/pkg/agentconfig/workflow.go
source_path: pkg/agentconfig/workflow.go
generated: true
---
- Path: `+"`pkg/agentconfig/workflow.go`"+`
`)

	svc := NewService(Config{RepoPath: repo})
	resp := svc.Status(context.Background(), StatusRequest{})
	if !resp.OK {
		t.Fatalf("status OK = false, error = %#v", resp.Error)
	}
	result := resp.Result.(StatusResult)
	if result.CodeConceptCount != 1 {
		t.Fatalf("code_concept_count = %d, want 1", result.CodeConceptCount)
	}
}

// TestStatusOmitsCodeConceptCountWhenNone verifies the field is omitted (zero)
// when the bundle has no code_file concepts.
func TestStatusOmitsCodeConceptCountWhenNone(t *testing.T) {
	repo := initToolTestRepo(t)
	mustWriteToolFile(t, filepath.Join(repo, ".okf", "knowledge", "concepts", "alpha.md"), `---
type: concept
title: Alpha
---
Alpha content.
`)

	svc := NewService(Config{RepoPath: repo})
	resp := svc.Status(context.Background(), StatusRequest{})
	result := resp.Result.(StatusResult)
	if result.CodeConceptCount != 0 {
		t.Fatalf("code_concept_count = %d, want 0", result.CodeConceptCount)
	}
}

// TestFilteredConceptsBackwardCompat verifies that plain (non-code) concepts
// keep their existing Type / Types / Tag filtering behavior.
func TestFilteredConceptsBackwardCompat(t *testing.T) {
	alpha := &okf.Concept{Type: "concept", Title: "Alpha", Tags: []string{"code"}, Content: "alpha"}
	beta := &okf.Concept{Type: "note", Title: "Beta", Tags: []string{"docs"}, Content: "beta"}
	concepts := []*okf.Concept{alpha, beta}

	if got := filteredConceptsForQuery(concepts, queryFilters{Type: "concept"}); len(got) != 1 || got[0] != alpha {
		t.Fatalf("Type filter = %#v, want only alpha", got)
	}
	if got := filteredConceptsForQuery(concepts, queryFilters{Types: []string{"note"}}); len(got) != 1 || got[0] != beta {
		t.Fatalf("Types filter = %#v, want only beta", got)
	}
	if got := filteredConceptsForQuery(concepts, queryFilters{Tag: "code"}); len(got) != 1 || got[0] != alpha {
		t.Fatalf("Tag filter = %#v, want only alpha", got)
	}
	// Empty filters must return everything unchanged.
	if got := filteredConceptsForQuery(concepts, queryFilters{}); len(got) != 2 {
		t.Fatalf("empty filters = %d concepts, want 2", len(got))
	}
}

// TestFilteredConceptsNoFalsePositive verifies symbolLocationFromContent does
// not fabricate a location when no symbol name matches the query.
func TestFilteredConceptsNoFalsePositive(t *testing.T) {
	start, end, kind, name := symbolLocationFromContent(codeFileWorkflowContent, "RenderCodexMCPTOML")
	if start != 159 || end != 177 || kind != "function" || name != "RenderCodexMCPTOML" {
		t.Fatalf("matching symbol = %d-%d %q %q, want 159-177 function RenderCodexMCPTOML", start, end, kind, name)
	}

	start, end, kind, name = symbolLocationFromContent(codeFileWorkflowContent, "NoSuchSymbol")
	if start != 0 || end != 0 || kind != "" || name != "" {
		t.Fatalf("non-matching symbol = %d-%d %q %q, want 0,0", start, end, kind, name)
	}
}
