#!/usr/bin/env bash
# Real-agent acceptance for OKF Agent Integration.
# This test intentionally starts official agent CLIs. It does not use tools/mcp_call.py.
set -euo pipefail

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
OUT_DIR=${OKF_REAL_AGENT_EVIDENCE_DIR:-"$ROOT/.artifacts/real-agent-e2e"}
REAL_AGENT_EVIDENCE=${OKF_REAL_AGENT_EVIDENCE_MD:-"$ROOT/openspec/changes/add-agent-knowledge-discovery/real-agent-evidence.md"}
SOURCE_COMMIT=$(git -C "$ROOT" rev-parse HEAD)
SOURCE_DIRTY=false
if [[ -n "$(git -C "$ROOT" status --porcelain --untracked-files=all)" ]]; then SOURCE_DIRTY=true; fi
SOURCE_TREE_SHA256=$(cd "$ROOT" && python3 - <<'PY'
import hashlib, os, pathlib, subprocess
excluded={
 'openspec/changes/add-agent-knowledge-discovery/evidence.md',
 'openspec/changes/add-agent-knowledge-discovery/real-agent-evidence.md',
}
paths=subprocess.check_output(['git','ls-files','--cached','--others','--exclude-standard','-z']).decode().split('\0')
h=hashlib.sha256()
for value in sorted(p for p in paths if p and p not in excluded):
    p=pathlib.Path(value)
    h.update(value.encode()); h.update(b'\0')
    if p.is_symlink(): h.update(os.readlink(p).encode())
    else: h.update(p.read_bytes())
    h.update(b'\0')
print(h.hexdigest())
PY
)
RUN_TS=$(date -u +%Y-%m-%dT%H:%M:%SZ)
KEEP_WORKDIR=${OKF_REAL_AGENT_KEEP_WORKDIR:-0}
WORK_DIR=$(mktemp -d "${TMPDIR:-/tmp}/okf-real-agent-e2e.XXXXXX")
BIN="$WORK_DIR/bin/okf"
if [[ -z "$OUT_DIR" || "$OUT_DIR" == "/" ]]; then
  printf 'unsafe OKF_REAL_AGENT_EVIDENCE_DIR: %q\n' "$OUT_DIR" >&2
  exit 64
fi
mkdir -p "$WORK_DIR/bin" "$OUT_DIR"
for owned_evidence in \
  results.tsv summary.json okf-agent-apply.txt okf-init.txt \
  codex-mcp-list.json claude-mcp-list.txt claude-auth.json \
  cursor-mcp-list.txt cursor-auth.txt \
  codex-read.jsonl codex-read.stderr \
  codex-recovery.jsonl codex-recovery.stderr \
  codex-write.jsonl codex-write.stderr \
  codex-code-symbol.jsonl codex-code-symbol.stderr \
  codex-propagate.jsonl codex-propagate.stderr; do
  rm -f "$OUT_DIR/$owned_evidence"
done

cleanup() {
  if [[ "$KEEP_WORKDIR" != "1" ]]; then
    rm -rf "$WORK_DIR"
  else
    printf 'real-agent workdir retained: %s\n' "$WORK_DIR" >&2
  fi
}
trap cleanup EXIT

pass=0
fail=0
blocked=0
results="$OUT_DIR/results.tsv"
: > "$results"

record() {
  local client=$1 layer=$2 status=$3 detail=$4
  printf '%s\t%s\t%s\t%s\n' "$client" "$layer" "$status" "$detail" >> "$results"
  case "$status" in
    PASS) pass=$((pass + 1)) ;;
    BLOCKED_*) blocked=$((blocked + 1)) ;;
    *) fail=$((fail + 1)) ;;
  esac
  printf '%-12s %-20s %-16s %s\n' "$client" "$layer" "$status" "$detail"
}

find_claude() {
  if command -v claude >/dev/null 2>&1; then command -v claude; return; fi
  local isolated="$HOME/.local/share/okf-agent-e2e/claude/node_modules/.bin/claude"
  [[ -x "$isolated" ]] && printf '%s\n' "$isolated"
}

find_cursor() {
  if command -v cursor-agent >/dev/null 2>&1; then command -v cursor-agent; return; fi
  # Only accept a binary literally named "cursor-agent" or the well-known
  # Cursor Agent path; a bare `agent` is too generic and may match unrelated tools.
  [[ -x "$HOME/.local/bin/cursor-agent" ]] && printf '%s\n' "$HOME/.local/bin/cursor-agent"
}

# Build exactly the source tree under test.
go build -o "$BIN" ./cmd/okf

REPO="$WORK_DIR/repo"
mkdir -p "$REPO/docs" "$REPO/.okf/knowledge"
git -C "$REPO" init -q
git -C "$REPO" config user.email okf-agent-e2e@example.invalid
git -C "$REPO" config user.name okf-agent-e2e
cat > "$REPO/docs/orbital-runbook.txt" <<'DATA'
Orbital relay operations handbook.
For a lunar relay timeout, emergency_phrase=COBALT-ORBIT-7319; first_action=rotate the beacon key, then retry exactly once.
DATA
cat > "$REPO/.okf/knowledge/canary.md" <<'DATA'
---
type: concept
title: Orbital Canary Runbook
tags: [agent-e2e, canary]
okf_id: okf_0123456789abcdef0123456789abcdef
source_path: docs/orbital-runbook.txt
---
For a lunar relay timeout, emergency_phrase=COBALT-ORBIT-7319; first_action=rotate the beacon key, then retry exactly once.
DATA
git -C "$REPO" add -A
git -C "$REPO" commit -q -m 'agent e2e fixture'
PATH="$WORK_DIR/bin:$PATH" "$BIN" agent apply --client all --repo "$REPO" --yes > "$OUT_DIR/okf-agent-apply.txt"

# Code-symbol fixture: a tiny, self-contained Go module whose AST the okf Go
# extractor indexes into a code_file concept. Unlike the canary above (a
# hand-authored .okf/knowledge markdown), code knowledge is generated by
# `okf init`, so we must run it here -- after `agent apply` and before Codex
# runs. init leaves the hand-authored canary.md untouched and only adds
# generated concepts under .okf/knowledge/pkg and .okf/knowledge/project.
mkdir -p "$REPO/pkg/codexcfg"
cat > "$REPO/go.mod" <<'DATA'
module okf-real-agent-e2e

go 1.21
DATA
cat > "$REPO/pkg/codexcfg/workflow.go" <<'DATA'
// Package codexcfg is the throwaway code-symbol E2E fixture. It is generated
// into a scratch git repo by tools/verify-real-agent-e2e.sh; it is not part of
// the okf source tree. The okf Go AST extractor indexes its symbols so the
// official Codex MCP acceptance test can prove end-to-end code retrieval.
package codexcfg

import "fmt"

// RenderCodexMCPTOML renders the Codex MCP server TOML block. Its body carries
// the acceptance canaries: the exact args array and the OKF_MANAGED ownership
// literal that the real renderer emits.
func RenderCodexMCPTOML() string {
	args := []string{"mcp", "--repo", "."}
	OKF_MANAGED := "agentconfig-v1"
	return fmt.Sprintf("args=%v ownership=%s", args, OKF_MANAGED)
}

// propagateParentIDs walks child nodes and copies each node's parent OKF id
// downward so children inherit parent IDs without mutating the source graph.
func propagateParentIDs(childIDs []string, parentOKFID string) []string {
	propagated := make([]string, 0, len(childIDs))
	for _, child := range childIDs {
		propagated = append(propagated, child, parentOKFID)
	}
	return propagated
}
DATA
git -C "$REPO" add -A
git -C "$REPO" commit -q -m 'code-symbol e2e fixture'
if ! PATH="$WORK_DIR/bin:$PATH" "$BIN" init --repo "$REPO" > "$OUT_DIR/okf-init.txt" 2>&1; then
  record adapter code_knowledge_init FAIL 'okf init did not generate code concepts for the Go fixture'
else
  record adapter code_knowledge_init PASS 'okf init generated code_file concepts from the Go fixture'
fi

# Deterministic format parsing is a prerequisite, not Agent E2E evidence.
if python3 - "$REPO" <<'PY'
import json, pathlib, sys, tomllib
repo = pathlib.Path(sys.argv[1])
cursor = json.load(open(repo / '.cursor/mcp.json'))['mcpServers']['okf']
claude = json.load(open(repo / '.mcp.json'))['mcpServers']['okf']
codex = tomllib.load(open(repo / '.codex/config.toml', 'rb'))['mcp_servers']['okf']
for cfg in (cursor, claude, codex):
    assert cfg['command'] == 'okf', cfg
    assert cfg['args'] == ['mcp', '--repo', '.'], cfg
PY
then
  record adapter generated_config_parse PASS 'cursor/claude/codex configs parse with standard parsers'
else
  record adapter generated_config_parse FAIL 'generated project configuration is not parseable'
fi

CODEX=${CODEX_BIN:-$(command -v codex || true)}
CLAUDE=${CLAUDE_BIN:-$(find_claude || true)}
CURSOR=${CURSOR_BIN:-$(find_cursor || true)}
[[ -n "$CODEX" && -x "$CODEX" ]] || CODEX=""
[[ -n "$CLAUDE" && -x "$CLAUDE" ]] || CLAUDE=""
[[ -n "$CURSOR" && -x "$CURSOR" ]] || CURSOR=""

# Official-client discovery. These checks prove only that the official CLI consumed
# the generated project config; they are deliberately separate from model E2E.
if [[ -n "$CODEX" ]]; then
  CODEX_HOME_E2E="$HOME/.cache/okf-agent-e2e/codex-home-$PPID-$$"
  mkdir -p "$CODEX_HOME_E2E"
  if [[ -f "$HOME/.codex/config.toml" ]]; then cp "$HOME/.codex/config.toml" "$CODEX_HOME_E2E/config.toml"; else : > "$CODEX_HOME_E2E/config.toml"; fi
  printf '\n[projects."%s"]\ntrust_level = "trusted"\n' "$REPO" >> "$CODEX_HOME_E2E/config.toml"
  if (cd "$REPO" && PATH="$WORK_DIR/bin:$PATH" CODEX_HOME="$CODEX_HOME_E2E" "$CODEX" mcp list --json > "$OUT_DIR/codex-mcp-list.json") &&
     python3 - "$OUT_DIR/codex-mcp-list.json" <<'PY'
import json, sys
assert any(item.get('name') == 'okf' for item in json.load(open(sys.argv[1])))
PY
  then
    record codex official_config_discovery PASS 'official Codex CLI discovered project MCP server okf'
  else
    record codex official_config_discovery FAIL 'official Codex CLI did not discover okf'
  fi
else
  record codex official_config_discovery BLOCKED_CLIENT_MISSING 'codex executable not installed'
fi

if [[ -n "$CLAUDE" ]]; then
  if (cd "$REPO" && PATH="$WORK_DIR/bin:$PATH" "$CLAUDE" mcp list > "$OUT_DIR/claude-mcp-list.txt" 2>&1) && grep -q '^okf:' "$OUT_DIR/claude-mcp-list.txt"; then
    record claude-code official_config_discovery PASS 'official Claude Code CLI discovered okf (approval state recorded)'
  else
    record claude-code official_config_discovery FAIL 'official Claude Code CLI did not discover okf'
  fi
  "$CLAUDE" auth status > "$OUT_DIR/claude-auth.json" 2>&1 || true
else
  record claude-code official_config_discovery BLOCKED_CLIENT_MISSING 'claude executable not installed'
fi

if [[ -n "$CURSOR" ]]; then
  if (cd "$REPO" && PATH="$WORK_DIR/bin:$PATH" "$CURSOR" mcp list > "$OUT_DIR/cursor-mcp-list.txt" 2>&1) && grep -q '^okf:' "$OUT_DIR/cursor-mcp-list.txt"; then
    record cursor official_config_discovery PASS 'official Cursor Agent CLI discovered okf (approval state recorded)'
  else
    record cursor official_config_discovery FAIL 'official Cursor Agent CLI did not discover okf'
  fi
  "$CURSOR" status > "$OUT_DIR/cursor-auth.txt" 2>&1 || true
else
  record cursor official_config_discovery BLOCKED_CLIENT_MISSING 'cursor-agent executable not installed'
fi

validate_codex_read() {
  python3 - "$1" <<'PY'
import json, string, sys
calls, unexpected, final = [], [], ''
for line in open(sys.argv[1]):
    event = json.loads(line); item = event.get('item', {})
    if event.get('type') == 'item.completed' and item.get('type') == 'mcp_tool_call':
        calls.append((item.get('server'), item.get('tool'), item.get('status'), item.get('error')))
    if event.get('type') == 'item.completed' and item.get('type') not in {'mcp_tool_call','agent_message','reasoning'}:
        unexpected.append(item)
    if event.get('type') == 'item.completed' and item.get('type') == 'agent_message': final = item.get('text', '')
assert [(x[0], x[1]) for x in calls] == [('okf','okf_status'),('okf','okf_manifest'),('okf','okf_query'),('okf','okf_context')], calls
assert all(x[2] == 'completed' and not x[3] for x in calls), calls
assert not unexpected, unexpected
answer = None
try:
    answer = json.loads(final)
except json.JSONDecodeError:
    values = {}
    for line in final.splitlines():
        clean = line.strip().lstrip('-').strip().replace('`', '')
        sep = '=' if '=' in clean else (':' if ':' in clean else None)
        if sep:
            key, value = clean.split(sep, 1)
            values[key.strip()] = value.strip()
    answer = {
        'emergency_phrase': values.get('emergency_phrase', ''),
        'first_action': values.get('first_action', ''),
        'stable_ref': values.get('stable_ref', ''),
    }
assert answer['emergency_phrase'] == 'COBALT-ORBIT-7319', answer
assert answer['first_action'].rstrip(string.whitespace + string.punctuation).lower() == 'rotate the beacon key, then retry exactly once', answer
assert answer['stable_ref'] == 'okf://concept/okf_0123456789abcdef0123456789abcdef', answer
PY
}

validate_codex_recovery() {
  python3 - "$1" <<'PY'
import json, re, sys
calls, unexpected, final, first = [], [], '', None
for line in open(sys.argv[1]):
    event = json.loads(line); item = event.get('item', {})
    if event.get('type') == 'item.completed' and item.get('type') == 'mcp_tool_call':
        calls.append((item.get('server'), item.get('tool'), item.get('status'), item.get('error')))
        if len(calls) == 1: first = json.loads(item['result']['content'][0]['text'])
    if event.get('type') == 'item.completed' and item.get('type') not in {'mcp_tool_call','agent_message','reasoning'}:
        unexpected.append(item)
    if event.get('type') == 'item.completed' and item.get('type') == 'agent_message': final = item.get('text', '')
assert [(x[0], x[1]) for x in calls] == [('okf','okf_resolve'),('okf','okf_manifest'),('okf','okf_resolve')], calls
assert all(x[2] == 'completed' and not x[3] for x in calls), calls
assert not unexpected, unexpected
assert first['ok'] is False and first['error']['code'] == 'invalid_concept_id' and first['error']['remediation']
answer = None
try:
    answer = json.loads(final)
except json.JSONDecodeError:
    fenced = re.search(r'```(?:json)?\s*(\{.*?\})\s*```', final, re.DOTALL)
    if fenced:
        answer = json.loads(fenced.group(1))
    else:
        values = {}
        for line in final.splitlines():
            clean = line.strip().lstrip('-').strip().replace('`', '')
            sep = '=' if '=' in clean else (':' if ':' in clean else None)
            if sep:
                key, value = clean.split(sep, 1)
                values[key.strip()] = value.strip()
        answer = {
            'error_code': values.get('error_code', ''),
            'had_remediation': values.get('had_remediation', values.get('remediation_non_empty', '')).lower() == 'true',
            'resolved_path': values.get('resolved_path', ''),
        }
if 'had_remediation' not in answer and 'remediation_non_empty' in answer:
    answer['had_remediation'] = answer['remediation_non_empty']
assert answer.get('error_code') == 'invalid_concept_id' and answer.get('had_remediation') is True, answer
assert answer.get('resolved_path') == 'canary.md', answer
PY
}

validate_codex_write() {
  python3 - "$1" "$REPO" <<'PY'
import glob, json, pathlib, sys
calls, unexpected, final = [], [], ''
for line in open(sys.argv[1]):
    event = json.loads(line); item = event.get('item', {})
    if event.get('type') == 'item.completed' and item.get('type') == 'mcp_tool_call': calls.append((item.get('server'), item.get('tool'), item.get('status'), item.get('error')))
    if event.get('type') == 'item.completed' and item.get('type') not in {'mcp_tool_call','agent_message','reasoning'}:
        unexpected.append(item)
    if event.get('type') == 'item.completed' and item.get('type') == 'agent_message': final = item.get('text', '')
assert [(x[0], x[1]) for x in calls] == [('okf','okf_note'),('okf','okf_query')], calls
assert all(x[2] == 'completed' and not x[3] for x in calls), calls
assert not unexpected, unexpected
assert 'created=true' in final.lower() and 'HELIOS-WRITE-8842' in final, final
files = glob.glob(str(pathlib.Path(sys.argv[2]) / '.okf/knowledge/notes/*.md'))
assert len(files) == 1 and 'HELIOS-WRITE-8842' in open(files[0]).read(), files
PY
}

# Code-symbol E2E validator. Verifies the official Codex used ONLY the OKF MCP
# tool sequence, consumed a non-empty okf_query hit against the generated
# code_file concept, and returned values that match the fixture. Line numbers
# are recomputed from the fixture Go file (brace-matched) and tolerated against
# the ±1 surrounding-line window that okf_context emits around a function.
# Args: mode (render|propagate) jsonl repo symbol_name
validate_codex_code_symbol() {
  local mode=$1 jsonl=$2 repo=$3 symbol=$4
  python3 - "$mode" "$jsonl" "$repo" "$symbol" <<'PY'
import json, pathlib, re, sys
mode, event_path, repo, symbol = sys.argv[1], pathlib.Path(sys.argv[2]), pathlib.Path(sys.argv[3]), sys.argv[4]

# --- Recompute the function's true 1-indexed lines from the fixture. ---
# The fixture is Go; strip // comments, raw backtick strings and "..." strings
# so brace counting is not fooled by literals such as []string{"mcp", ...}.
src_lines = (repo / 'pkg/codexcfg/workflow.go').read_text().split('\n')
def strip_go(line):
    line = re.sub(r'`[^`]*`', '""', line)          # raw strings
    line = re.sub(r'"(?:\\.|[^"\\])*"', '""', line) # interpreted strings
    line = re.sub(r'//.*$', '', line)               # line comments
    return line
decl = close = None
target = f'func {symbol}('
for i, raw in enumerate(src_lines, 1):
    if raw.lstrip().startswith(target):
        decl = i
        depth = 0
        started = False
        for j in range(i, len(src_lines) + 1):
            for ch in strip_go(src_lines[j - 1]):
                if ch == '{':
                    depth += 1
                    started = True
                elif ch == '}':
                    depth -= 1
            if started and depth == 0:
                close = j
                break
        break
assert decl is not None and close is not None, f'symbol {symbol} not found in fixture'

# --- Parse the Codex JSONL event stream. ---
calls, unexpected, final, query_result = [], [], '', None
for line in open(event_path):
    event = json.loads(line); item = event.get('item', {})
    if event.get('type') == 'item.completed' and item.get('type') == 'mcp_tool_call':
        calls.append((item.get('server'), item.get('tool'), item.get('status'), item.get('error')))
        if item.get('tool') == 'okf_query':
            try:
                query_result = json.loads(item['result']['content'][0]['text'])
            except Exception:
                query_result = None
    if event.get('type') == 'item.completed' and item.get('type') not in {'mcp_tool_call','agent_message','reasoning'}:
        unexpected.append(item)
    if event.get('type') == 'item.completed' and item.get('type') == 'agent_message':
        final = item.get('text', '')

if mode == 'render':
    expected = [('okf','okf_status'),('okf','okf_manifest'),('okf','okf_query'),('okf','okf_context')]
else:
    expected = [('okf','okf_query'),('okf','okf_context')]
assert [(x[0], x[1]) for x in calls] == expected, calls
assert all(x[2] == 'completed' and not x[3] for x in calls), calls
assert not unexpected, unexpected

# okf_query must have returned a non-empty code_file hit for this symbol.
assert query_result is not None, 'okf_query result missing from event stream'
hits = (query_result.get('result') or query_result).get('results') or []
code_hits = [h for h in hits if h.get('type') == 'code_file' and h.get('qualified_name') == symbol]
assert code_hits, f'okf_query did not hit a code_file concept for {symbol}: {hits}'
assert code_hits[0].get('start_line') == decl and code_hits[0].get('end_line') == close, code_hits[0]

# --- Parse the final answer (JSON, fenced JSON, key=value, or regex fallback). ---
answer = None
try:
    answer = json.loads(final)
except json.JSONDecodeError:
    fenced = re.search(r'```(?:json)?\s*(\{.*?\})\s*```', final, re.DOTALL)
    if fenced:
        try: answer = json.loads(fenced.group(1))
        except json.JSONDecodeError: pass
if not isinstance(answer, dict):
    values = {}
    for raw in final.splitlines():
        clean = raw.strip().lstrip('-').strip().replace('`', '').replace('*', '')
        sep = '=' if '=' in clean else (':' if ':' in clean else None)
        if sep:
            k, v = clean.split(sep, 1)
            values[k.strip().lower()] = v.strip()
    answer = values

# Regex fallback: extract fields directly from the raw text when the model
# returns markdown / prose instead of clean JSON. The MCP call sequence and
# okf_query result are already validated above; this only needs to confirm the
# model read the correct values from the context snippet.
raw = final.replace('`', '').replace('*', '')

def num(*names):
    for n in names:
        if n in answer:
            try: return int(answer[n])
            except (TypeError, ValueError): pass
    # regex search in raw text: start_line: 12 or start_line = 12
    for n in names:
        m = re.search(rf'{n}\s*[:=]\s*(\d+)', raw, re.IGNORECASE)
        if m: return int(m.group(1))
    return None

start_line = num('start_line', 'startline', 'start')
end_line = num('end_line', 'endline', 'end')
# okf_context emits [decl-1, close]; a correct model may report either the
# snippet window or the bare function range. Accept the honest ±1 bracketing.
assert start_line is not None and end_line is not None, (answer, start_line, end_line)
assert decl - 1 <= start_line <= decl, (start_line, decl, answer)
assert close <= end_line <= close + 1, (end_line, close, answer)

if mode == 'render':
    args = answer.get('args')
    if isinstance(args, str):
        m = re.search(r'\[[^\]]*\]', args)
        flat = m.group(0) if m else args
    elif isinstance(args, list):
        flat = json.dumps(args)
    else:
        # regex: find the three string literals in order, regardless of
        # whether they are wrapped as JSON ["mcp", ...] or Go []string{"mcp", ...}.
        m = re.search(r'"mcp"\s*,\s*"--repo"\s*,\s*"\."', raw)
        assert m, f'args not found in answer: {final[:200]}'
        flat = '["mcp", "--repo", "."]'
    assert list(json.loads(flat)) == ['mcp', '--repo', '.'], args
    okf_managed = str(answer.get('okf_managed', answer.get('ownership', '')))
    if 'agentconfig-v1' not in okf_managed:
        assert 'agentconfig-v1' in raw, f'ownership not found in answer: {final[:200]}'
else:
    behavior = str(answer.get('behavior', answer.get('description', ''))).lower()
    if not ('parent' in behavior and 'propagat' in behavior):
        assert 'parent' in raw.lower() and 'propagat' in raw.lower(), f'behavior not found in answer: {final[:200]}'
PY
}

validate_generic_agent_stream() {
  local mode=$1 jsonl=$2 repo=$3 expected_write_canary=${4:-}
  python3 - "$mode" "$jsonl" "$repo" "$expected_write_canary" <<'PY'
import json, pathlib, re, sys
mode, event_path, repo, expected_write_canary = sys.argv[1], pathlib.Path(sys.argv[2]), pathlib.Path(sys.argv[3]), sys.argv[4]
events=[]
for line in event_path.read_text(errors='replace').splitlines():
    try: events.append(json.loads(line))
    except json.JSONDecodeError: pass
if not events:
    raise SystemExit('no machine-readable events')

def walk(value):
    if isinstance(value, dict):
        yield value
        for child in value.values(): yield from walk(child)
    elif isinstance(value, list):
        for child in value: yield from walk(child)

def normalize(name):
    name=str(name or '')
    for sep in ('__', '/', '.'):
        if sep in name: name=name.split(sep)[-1]
    return name

tool_names=[]
tool_result_text=[]
final_text=[]
forbidden_events=[]
for event in events:
    event_kind=str(event.get('type','')).lower()
    if event_kind == 'result' and isinstance(event.get('result'), str): final_text.append(event['result'])
    for obj in walk(event):
        kind=str(obj.get('type','')).lower()
        candidate=obj.get('tool') or obj.get('tool_name') or (obj.get('name') if kind in {'tool_use','tool_call','mcp_tool_call'} else None)
        if candidate: tool_names.append(normalize(candidate))
        if kind in {'tool_use','tool_call','mcp_tool_call','command_execution','file_read','file_write'} and candidate and not normalize(candidate).startswith('okf_'):
            forbidden_events.append((kind, normalize(candidate)))
        if 'tool_result' in kind or 'mcp_result' in kind:
            tool_result_text.append(json.dumps(obj, ensure_ascii=False))
        if kind == 'agent_message' or kind == 'assistant' or obj.get('role') == 'assistant':
            for key in ('text','result','output'):
                value=obj.get(key)
                if isinstance(value,str): final_text.append(value)
            content=obj.get('content')
            if isinstance(content,list):
                for block in content:
                    if isinstance(block,dict) and isinstance(block.get('text'),str): final_text.append(block['text'])
forbidden={'bash','shell','terminal','read','read_file','grep','exec','command_execution','python'}
if forbidden_events or any(name.lower() in forbidden for name in tool_names):
    raise SystemExit(f'forbidden bypass tool observed: events={forbidden_events} tools={tool_names}')
okf_tools=[name for name in tool_names if name.startswith('okf_')]
answer='\n'.join(final_text)
tool_results='\n'.join(tool_result_text)
if mode == 'read':
    expected=['okf_status','okf_manifest','okf_query','okf_context']
    if okf_tools != expected: raise SystemExit(f'wrong tool trace: {okf_tools}')
    for value in ('COBALT-ORBIT-7319','rotate the beacon key, then retry exactly once','okf://concept/okf_0123456789abcdef0123456789abcdef'):
        if value.lower() not in answer.lower(): raise SystemExit(f'missing final-answer value: {value}')
elif mode == 'recovery':
    expected=['okf_resolve','okf_manifest','okf_resolve']
    if okf_tools != expected: raise SystemExit(f'wrong tool trace: {okf_tools}')
    for value in ('invalid_concept_id','remediation'):
        if value.lower() not in tool_results.lower(): raise SystemExit(f'missing structured tool error evidence: {value}')
    for value in ('invalid_concept_id','canary.md'):
        if value.lower() not in answer.lower(): raise SystemExit(f'missing final recovery evidence: {value}')
elif mode == 'write':
    expected=['okf_note','okf_query']
    if okf_tools != expected: raise SystemExit(f'wrong tool trace: {okf_tools}')
    if not expected_write_canary: raise SystemExit('expected write canary is empty')
    if expected_write_canary not in tool_results: raise SystemExit('write canary missing from tool results')
    if expected_write_canary not in answer: raise SystemExit('write canary missing from final answer')
    notes=list(repo.glob('.okf/knowledge/notes/*.md'))
    if not notes or not any(expected_write_canary in note.read_text(errors='replace') for note in notes):
        raise SystemExit('durable note effect missing')
else:
    raise SystemExit(f'unknown validation mode: {mode}')
PY
}

run_official_model_matrix() {
  local client=$1 exe=$2
  local output_prefix="$OUT_DIR/${client//-/_}"
  local client_token=${client//-/_}
  local write_canary="HELIOS-WRITE-8842-${client_token}"
  local read_prompt='Strict OKF MCP read acceptance test. Do not use shell, terminal, direct file reads, or the okf CLI. Use only OKF MCP. Call exactly once and in order: okf_status; okf_manifest limit 5; okf_query query "lunar relay timeout" group_by "source"; okf_context query "lunar relay timeout" budget_tokens 500. Return the emergency phrase, first action, and stable ref.'
  local recovery_prompt='Strict OKF MCP recovery test. Use only OKF MCP. Resolve bad-ref, consume its structured error and remediation, call okf_manifest limit 5, then resolve the canonical stable ref. Return the error code, remediation presence, and resolved path.'
  local write_prompt="Strict OKF MCP controlled-write test. Use only OKF MCP. Call okf_note once with content \"Agent E2E durable note: $write_canary\", project \"orbital\", tags [\"agent-e2e\"], idempotency_key \"official-real-agent-note-${client_token}-v1\"; then call okf_query once for $write_canary and report the retrieved content."
  local -a base
  if [[ "$client" == "claude-code" ]]; then
    base=("$exe" -p --output-format stream-json --verbose --permission-mode dontAsk --permission-prompts none)
  else
    base=("$exe" -p --output-format stream-json --approve-mcps --trust --workspace "$REPO")
  fi
  local mode prompt
  for mode in read recovery write; do
    case "$mode" in read) prompt=$read_prompt ;; recovery) prompt=$recovery_prompt ;; write) prompt=$write_prompt ;; esac
    if (cd "$REPO" && PATH="$WORK_DIR/bin:$PATH" timeout 600 "${base[@]}" "$prompt" > "$output_prefix-$mode.jsonl" 2> "$output_prefix-$mode.stderr") && validate_generic_agent_stream "$mode" "$output_prefix-$mode.jsonl" "$REPO" "$write_canary"; then
      record "$client" "model_${mode}" PASS "official client stream validated; OKF MCP trace and final effect verified"
    else
      record "$client" "model_${mode}" FAIL "official client stream/tool/answer validation failed"
    fi
  done
}

# RED controls for the home-grown validators. Correct-looking final text without
# the required tool trace/effect must be rejected, otherwise Agent E2E can fail open.
validator_controls="$WORK_DIR/validator-controls"
mkdir -p "$validator_controls"
cat > "$validator_controls/read-without-tools.jsonl" <<'JSONL'
{"type":"item.completed","item":{"type":"agent_message","text":"emergency_phrase=COBALT-ORBIT-7319\nfirst_action=rotate the beacon key, then retry exactly once\nstable_ref=okf://concept/okf_0123456789abcdef0123456789abcdef"}}
JSONL
cat > "$validator_controls/recovery-without-error.jsonl" <<'JSONL'
{"type":"item.completed","item":{"type":"agent_message","text":"error_code=invalid_concept_id\nremediation_non_empty=true\nresolved_path=canary.md"}}
JSONL
cat > "$validator_controls/write-without-effect.jsonl" <<'JSONL'
{"type":"item.completed","item":{"type":"mcp_tool_call","server":"okf","tool":"okf_note","status":"completed","error":null}}
{"type":"item.completed","item":{"type":"mcp_tool_call","server":"okf","tool":"okf_query","status":"completed","error":null}}
{"type":"item.completed","item":{"type":"agent_message","text":"created=true HELIOS-WRITE-8842"}}
JSONL
cat > "$validator_controls/read-with-bypass.jsonl" <<'JSONL'
{"type":"item.completed","item":{"type":"mcp_tool_call","server":"okf","tool":"okf_status","status":"completed","error":null}}
{"type":"item.completed","item":{"type":"mcp_tool_call","server":"okf","tool":"okf_manifest","status":"completed","error":null}}
{"type":"item.completed","item":{"type":"mcp_tool_call","server":"okf","tool":"okf_query","status":"completed","error":null}}
{"type":"item.completed","item":{"type":"mcp_tool_call","server":"okf","tool":"okf_context","status":"completed","error":null}}
{"type":"item.completed","item":{"type":"file_read","name":"Read","text":"bypass"}}
{"type":"item.completed","item":{"type":"agent_message","text":"emergency_phrase=COBALT-ORBIT-7319\nfirst_action=rotate the beacon key, then retry exactly once\nstable_ref=okf://concept/okf_0123456789abcdef0123456789abcdef"}}
JSONL
# Code-symbol RED controls: a correct-looking answer without the required
# okf_query hit (fabricated from context alone) must be rejected, as must a
# stream that smuggles in a filesystem bypass tool.
cat > "$validator_controls/code-symbol-without-query.jsonl" <<'JSONL'
{"type":"item.completed","item":{"type":"mcp_tool_call","server":"okf","tool":"okf_status","status":"completed","error":null}}
{"type":"item.completed","item":{"type":"mcp_tool_call","server":"okf","tool":"okf_manifest","status":"completed","error":null}}
{"type":"item.completed","item":{"type":"mcp_tool_call","server":"okf","tool":"okf_context","status":"completed","error":null}}
{"type":"item.completed","item":{"type":"agent_message","text":"{\"args\":[\"mcp\",\"--repo\",\".\"],\"okf_managed\":\"agentconfig-v1\",\"start_line\":11,\"end_line\":16}"}}
JSONL
cat > "$validator_controls/code-symbol-with-bypass.jsonl" <<'JSONL'
{"type":"item.completed","item":{"type":"mcp_tool_call","server":"okf","tool":"okf_status","status":"completed","error":null}}
{"type":"item.completed","item":{"type":"mcp_tool_call","server":"okf","tool":"okf_manifest","status":"completed","error":null}}
{"type":"item.completed","item":{"type":"mcp_tool_call","server":"okf","tool":"okf_query","status":"completed","error":null,"result":{"content":[{"text":"{\"result\":{\"results\":[{\"type\":\"code_file\",\"qualified_name\":\"RenderCodexMCPTOML\",\"start_line\":12,\"end_line\":16}]}}"}]}}}
{"type":"item.completed","item":{"type":"mcp_tool_call","server":"okf","tool":"okf_context","status":"completed","error":null}}
{"type":"item.completed","item":{"type":"shell","name":"Bash","text":"cat pkg/codexcfg/workflow.go"}}
{"type":"item.completed","item":{"type":"agent_message","text":"{\"args\":[\"mcp\",\"--repo\",\".\"],\"okf_managed\":\"agentconfig-v1\",\"start_line\":11,\"end_line\":16}"}}
JSONL
if validate_codex_read "$validator_controls/read-without-tools.jsonl" >/dev/null 2>&1 ||
   validate_codex_read "$validator_controls/read-with-bypass.jsonl" >/dev/null 2>&1 ||
   validate_codex_recovery "$validator_controls/recovery-without-error.jsonl" >/dev/null 2>&1 ||
   validate_codex_write "$validator_controls/write-without-effect.jsonl" >/dev/null 2>&1 ||
   validate_generic_agent_stream read "$validator_controls/read-without-tools.jsonl" "$REPO" unused >/dev/null 2>&1 ||
   validate_generic_agent_stream recovery "$validator_controls/recovery-without-error.jsonl" "$REPO" unused >/dev/null 2>&1 ||
   validate_generic_agent_stream write "$validator_controls/write-without-effect.jsonl" "$REPO" HELIOS-WRITE-8842 >/dev/null 2>&1 ||
   validate_codex_code_symbol render "$validator_controls/code-symbol-without-query.jsonl" "$REPO" RenderCodexMCPTOML >/dev/null 2>&1 ||
   validate_codex_code_symbol render "$validator_controls/code-symbol-with-bypass.jsonl" "$REPO" RenderCodexMCPTOML >/dev/null 2>&1; then
  record validator negative_controls FAIL 'a home-grown Agent evidence validator accepted fabricated evidence'
else
  record validator negative_controls PASS 'fabricated answer/recovery/write/code-symbol evidence is rejected'
fi

# Actual Codex model E2E. Authentication/provider availability is an explicit
# capability prerequisite; absence is BLOCKED_AUTH, never PASS.
if [[ -n "$CODEX" ]] && [[ -n "${XEART_API_KEY:-${OPENAI_API_KEY:-${CODEX_API_KEY:-}}}" ]]; then
  cat > "$WORK_DIR/read-schema.json" <<'JSON'
{"type":"object","additionalProperties":false,"required":["emergency_phrase","first_action","stable_ref","tools_used"],"properties":{"emergency_phrase":{"type":"string"},"first_action":{"type":"string"},"stable_ref":{"type":"string"},"tools_used":{"type":"array","items":{"type":"string"}}}}
JSON
  read_prompt='Strict OKF MCP read acceptance test. Do not use shell, exec, terminal, cat, grep, Python, direct filesystem reads, or the okf CLI. Use only MCP tools from server okf. Call exactly once and in order: okf_status; okf_manifest with limit 5; okf_query with query "lunar relay timeout" and group_by "source"; okf_context with query "lunar relay timeout" and budget_tokens 500. Do not call any other tool. The context evidence contains explicit fields emergency_phrase=... and first_action=.... Copy their values exactly. stable_ref must come from manifest.'
  if (cd "$REPO" && PATH="$WORK_DIR/bin:$PATH" CODEX_HOME="$CODEX_HOME_E2E" timeout 600 "$CODEX" exec --json --ephemeral --output-schema "$WORK_DIR/read-schema.json" -C "$REPO" -s read-only -c 'approval_policy="never"' "$read_prompt" > "$OUT_DIR/codex-read.jsonl" 2> "$OUT_DIR/codex-read.stderr") && validate_codex_read "$OUT_DIR/codex-read.jsonl"; then
    record codex model_read_answer PASS 'real Agent called status→manifest→query→context; no shell; answer correct'
  else
    record codex model_read_answer FAIL 'Codex model read/tool/answer closure failed'
  fi

  cat > "$WORK_DIR/recovery-schema.json" <<'JSON'
{"type":"object","additionalProperties":false,"required":["error_code","had_remediation","resolved_path"],"properties":{"error_code":{"type":"string"},"had_remediation":{"type":"boolean"},"resolved_path":{"type":"string"}}}
JSON
  recovery_prompt='Strict OKF MCP error-recovery acceptance test. Do not use shell, exec, terminal, direct filesystem reads, Python, or the okf CLI. Use only MCP tools from server okf. First call okf_resolve exactly once with ref "bad-ref" and inspect the structured error and remediation. Then call okf_manifest exactly once with limit 5, obtain the stable ref for Orbital Canary Runbook, and call okf_resolve exactly once with that stable ref. Do not call any other tool. Return error_code, whether remediation was non-empty, and resolved_path.'
  if (cd "$REPO" && PATH="$WORK_DIR/bin:$PATH" CODEX_HOME="$CODEX_HOME_E2E" timeout 600 "$CODEX" exec --json --ephemeral --output-schema "$WORK_DIR/recovery-schema.json" -C "$REPO" -s read-only -c 'approval_policy="never"' "$recovery_prompt" > "$OUT_DIR/codex-recovery.jsonl" 2> "$OUT_DIR/codex-recovery.stderr") && validate_codex_recovery "$OUT_DIR/codex-recovery.jsonl"; then
    record codex model_error_recovery PASS 'real Agent consumed structured error/remediation and retried successfully'
  else
    record codex model_error_recovery FAIL 'Codex structured error recovery failed'
  fi

  write_prompt='Strict OKF MCP controlled-write acceptance test. Do not use shell, exec, terminal, direct filesystem reads/writes, Python, or the okf CLI. Use only MCP tools from server okf. First call okf_note exactly once with content "Agent E2E durable note: HELIOS-WRITE-8842", project "orbital", tags ["agent-e2e"], and idempotency_key "codex-real-agent-note-v1". Then call okf_query exactly once with query "HELIOS-WRITE-8842", project "orbital", and limit 5. Do not call any other tool. Output created=true only when the write created a concept, followed by the retrieved note content.'
  if (cd "$REPO" && PATH="$WORK_DIR/bin:$PATH" CODEX_HOME="$CODEX_HOME_E2E" timeout 600 "$CODEX" exec --json --ephemeral --approve-for-me -C "$REPO" "$write_prompt" > "$OUT_DIR/codex-write.jsonl" 2> "$OUT_DIR/codex-write.stderr") && validate_codex_write "$OUT_DIR/codex-write.jsonl"; then
    record codex model_controlled_write PASS 'real Agent called note→query; persisted file and answer verified'
  else
    record codex model_controlled_write FAIL 'Codex controlled write/readback closure failed'
  fi

  # Code-symbol E2E against the generated code_file concept. The symbol_kind
  # filter is "function" (the value the okf Go AST extractor emits; "func"
  # filters to zero hits against the real generator output).
  cat > "$WORK_DIR/code-symbol-schema.json" <<'JSON'
{"type":"object","additionalProperties":false,"required":["args","okf_managed","start_line","end_line"],"properties":{"args":{"type":"array","items":{"type":"string"}},"okf_managed":{"type":"string"},"start_line":{"type":"integer"},"end_line":{"type":"integer"}}}
JSON
  code_symbol_prompt='Strict OKF MCP code-symbol acceptance test. Do not use shell, exec, terminal, direct filesystem reads, Python, or the okf CLI. Use only MCP tools from server okf. Call exactly once and in order: okf_status; okf_manifest with limit 10; okf_query with query "RenderCodexMCPTOML" file_path "pkg/codexcfg/workflow.go" symbol_kind "function" qualified_name "RenderCodexMCPTOML"; okf_context with query "RenderCodexMCPTOML" budget_tokens 800. Do not call any other tool. From the context source snippet, extract: (1) the exact args array value, (2) the OKF_MANAGED ownership value, (3) the function start_line and end_line.'
  if (cd "$REPO" && PATH="$WORK_DIR/bin:$PATH" CODEX_HOME="$CODEX_HOME_E2E" timeout 600 "$CODEX" exec --json --ephemeral --output-schema "$WORK_DIR/code-symbol-schema.json" -C "$REPO" -s read-only -c 'approval_policy="never"' "$code_symbol_prompt" > "$OUT_DIR/codex-code-symbol.jsonl" 2> "$OUT_DIR/codex-code-symbol.stderr") && validate_codex_code_symbol render "$OUT_DIR/codex-code-symbol.jsonl" "$REPO" RenderCodexMCPTOML; then
    record codex model_code_symbol PASS 'real Agent queried generated code_file concept; args, ownership, and line numbers verified'
  else
    record codex model_code_symbol FAIL 'Codex code-symbol query/context/answer closure failed'
  fi

  cat > "$WORK_DIR/propagate-schema.json" <<'JSON'
{"type":"object","additionalProperties":false,"required":["behavior","start_line","end_line"],"properties":{"behavior":{"type":"string"},"start_line":{"type":"integer"},"end_line":{"type":"integer"}}}
JSON
  propagate_prompt='Strict OKF MCP code-symbol acceptance test for propagateParentIDs. Do not use shell, exec, terminal, direct filesystem reads, Python, or the okf CLI. Use only MCP tools from server okf. Call exactly once and in order: okf_query with query "propagateParentIDs" file_path "pkg/codexcfg/workflow.go" symbol_kind "function" qualified_name "propagateParentIDs"; okf_context with query "propagateParentIDs" budget_tokens 800. Do not call any other tool. From the context source snippet, extract a one-line behavior description and the function start_line and end_line.'
  if (cd "$REPO" && PATH="$WORK_DIR/bin:$PATH" CODEX_HOME="$CODEX_HOME_E2E" timeout 600 "$CODEX" exec --json --ephemeral --output-schema "$WORK_DIR/propagate-schema.json" -C "$REPO" -s read-only -c 'approval_policy="never"' "$propagate_prompt" > "$OUT_DIR/codex-propagate.jsonl" 2> "$OUT_DIR/codex-propagate.stderr") && validate_codex_code_symbol propagate "$OUT_DIR/codex-propagate.jsonl" "$REPO" propagateParentIDs; then
    record codex model_propagate_parent_ids PASS 'real Agent retrieved propagateParentIDs snippet; behavior and line numbers verified'
  else
    record codex model_propagate_parent_ids FAIL 'Codex propagateParentIDs code-symbol closure failed'
  fi
else
  if [[ -z "$CODEX" ]]; then
    record codex model_e2e BLOCKED_CLIENT_MISSING 'codex executable not installed'
    record codex model_code_symbol BLOCKED_CLIENT_MISSING 'codex executable not installed'
    record codex model_propagate_parent_ids BLOCKED_CLIENT_MISSING 'codex executable not installed'
  else
    record codex model_e2e BLOCKED_AUTH 'no usable Codex model credential/provider exported'
    record codex model_code_symbol BLOCKED_AUTH 'no usable Codex model credential/provider exported'
    record codex model_propagate_parent_ids BLOCKED_AUTH 'no usable Codex model credential/provider exported'
  fi
fi

# Claude/Cursor inference tests cannot be honestly run without their official
# client authentication. The official config-discovery result above remains valid.
if [[ -z "$CLAUDE" ]]; then
  record claude-code model_e2e BLOCKED_CLIENT_MISSING 'claude executable not installed'
elif python3 - "$OUT_DIR/claude-auth.json" <<'PY'
import json, sys
try: assert json.load(open(sys.argv[1])).get('loggedIn') is True
except Exception: raise SystemExit(1)
PY
then
  run_official_model_matrix claude-code "$CLAUDE"
else
  record claude-code model_e2e BLOCKED_AUTH 'official client is not logged in'
fi
if [[ -z "$CURSOR" ]]; then
  record cursor model_e2e BLOCKED_CLIENT_MISSING 'cursor-agent executable not installed'
elif grep -qi 'logged in\|authenticated\|signed in' "$OUT_DIR/cursor-auth.txt" 2>/dev/null && ! grep -qi 'not logged in\|not authenticated\|signed out' "$OUT_DIR/cursor-auth.txt" 2>/dev/null; then
  run_official_model_matrix cursor "$CURSOR"
else
  record cursor model_e2e BLOCKED_AUTH 'official client login status could not be positively confirmed (fail-closed)'
fi

python3 - "$results" "$OUT_DIR/summary.json" "$REAL_AGENT_EVIDENCE" "$SOURCE_COMMIT" "$SOURCE_DIRTY" "$SOURCE_TREE_SHA256" "$RUN_TS" <<'PY'
import json, pathlib, sys
results_path = pathlib.Path(sys.argv[1])
summary_path = pathlib.Path(sys.argv[2])
evidence_path = pathlib.Path(sys.argv[3])
source_commit = sys.argv[4]
source_dirty = sys.argv[5].lower() == 'true'
source_tree_sha256 = sys.argv[6]
timestamp = sys.argv[7]
rows=[]
for line in results_path.read_text().splitlines():
    client, layer, status, detail = line.split('\t', 3)
    rows.append({'client':client,'layer':layer,'status':status,'detail':detail})
counts={k:sum(r['status']==k for r in rows) for k in sorted({r['status'] for r in rows})}
summary={'schema':'okf.real-agent-e2e.v1','source_commit':source_commit,'source_dirty':source_dirty,'source_tree_sha256':source_tree_sha256,'timestamp_utc':timestamp,'results':rows,'counts':counts}
summary_path.write_text(json.dumps(summary,indent=2)+'\n')
lines = [
    '# Real Agent Evidence — add-agent-knowledge-discovery (fresh run)',
    '',
    f'- Source commit: `{source_commit}`',
    f'- Source dirty: `{str(source_dirty).lower()}`',
    f'- Source tree SHA-256: `{source_tree_sha256}` (tracked + non-ignored untracked files; generated evidence excluded)',
    f'- Verification timestamp (UTC): {timestamp}',
    '- Entry point: `tools/verify-real-agent-e2e.sh`',
    '- Direct MCP helpers are excluded from Agent-client evidence.',
    '',
    '| Client | Layer | Status | Evidence |',
    '|---|---|---|---|',
]
for row in rows:
    detail = row['detail'].replace('|', '\\|')
    lines.append(f"| {row['client']} | {row['layer']} | {row['status']} | {detail} |")
lines += [
    '',
    '## Counts',
    '',
    '```json',
    json.dumps(counts, sort_keys=True),
    '```',
    '',
    'Strict release acceptance requires `REQUIRE_ALL_AGENT_MODELS=1` and exit code 0.',
]
evidence_path.write_text('\n'.join(lines)+'\n')
PY

rm -rf "${CODEX_HOME_E2E:-}"
printf '\nsummary: pass=%d fail=%d blocked=%d\nevidence-json: %s\nevidence-md: %s\n' "$pass" "$fail" "$blocked" "$OUT_DIR/summary.json" "$REAL_AGENT_EVIDENCE"
if (( fail != 0 )); then
  exit 1
fi
if [[ "${REQUIRE_ALL_AGENT_MODELS:-0}" == "1" ]] && (( blocked != 0 )); then
  printf 'strict release gate failed: %d Agent model E2E checks are BLOCKED\n' "$blocked" >&2
  exit 2
fi
