// Package okf implements the Open Knowledge Format (OKF) specification.
//
// OKF is an open, human- and agent-friendly format for representing knowledge
// as markdown files with YAML frontmatter. It is designed to be authored by
// people, generated by agents, exchanged across organizations, and consumed by both.
//
// The package provides:
//
//   - Core types: Concept, KnowledgeBundle, Query
//   - Parser: Markdown + YAML frontmatter parsing and serialization
//   - Query: Advanced search with type/tag/text/regex filters
//   - Lint: Specification compliance checking (13 rules)
//   - Git: Repository scanning and knowledge base generation
//
// Example usage:
//
//	import "github.com/superops-team/okf/pkg/okf"
//
//	// Parse a concept
//	concept, err := okf.ParseConcept("path/to/file.md")
//
//	// Load a knowledge bundle
//	bundle, err := okf.LoadBundle("/path/to/bundle", nil)
//
//	// Search
//	results := bundle.Search("database")
//
//	// Lint check
//	result := okf.LintBundle(bundle, nil)
//
// For CLI usage, see github.com/superops-team/okf/cmd/okf
package okf
